# [START runtime]
service: fintual-front
runtime: python27
threadsafe: yes
# [END runtime]
handlers:
- url: /
  static_files: dist/index.html
  upload: dist/index.html
- url: /(.*\.(js|css|svg|png|json|woff|jpg)(|\.map))$
  static_files: dist/\1
  upload: dist/(.*)(|\.map)
- url: /.*
  static_files: dist/index.html
  upload: dist/.*
skip_files:
- ^(?!dist)  # Skip any files not in the dist folder